
# CSE183 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8 Backend
  version: 0.1.0
  title: CSE183 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /listings:
    get:
      description: Gets all listings
      responses:
        200:
          description: Got all listings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listings'

components:
  schemas:
    Listings:
      properties:
        id:
          type: string
          format: uuid
        categoryID:
          type: string
          format: uuid
        memberID:
          type: string
          format: uuid
        listings:
          type: object  
      required:
        - id
        - categoryID
        - memberID
        - listings