# CSE183 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8 Backend
  version: 0.1.0
  title: CSE183 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /listings:
    get:
      description: Gets all listings
      security: []
      parameters:
      - name: search
        in: query
        description: Query search
        required: false
        schema:
          type: string
      - name: id
        in: query
        description: Listing ID
        required: false
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Got all listings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listings'
  /listings/category:
    get:
      description: Gets all categories
      security: []
      parameters:
      - name: sub
        in: query
        description: Finds sub of category
        required: false
        schema:
          type: string
      responses:
        200:
          description: Got all categories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
  /listings/{category}:
    get:
      description: Gets listings from category
      security: []
      parameters:
      - name: category
        in: path
        description: Name of category
        required: true
        schema:
          type: string
      - name: sub
        in: query
        description: Name of a subcategory
        required: false
        schema:
          type: string
      responses:
        200:
          description: Listings Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listings'
     
        404:
          description: Listings not found
  /member:
    get:
      description: Gets users
      security: []
      parameters:
      - name: user
        in: query
        description: specific user
        schema:
          type: string
      responses:
        200:
          description: got users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Members'
        404:
          description: Users not found

components:
  schemas:
    Categories:
      properties:
        parent:
          type: string
        name:
          type: string
        id:
          type: string
          format: uuid
      required:
        - parent
        - name
        - id
    Listings:
      properties:
        id:
          type: string
          format: uuid
        categoryID:
          type: string
          format: uuid
        memberID:
          type: string
          format: uuid
        listings:
          type: object  
      required:
        - id
        - categoryID
        - memberID
        - listings
    Members:
      properties:
        id:
          type: string
          format: uuid
        member:
          type: object
      required:
        - id
        - member
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer